"""initial

Revision ID: a1f5351e7701
Revises: 
Create Date: 2026-04-30 16:02:51.995938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a1f5351e7701'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_data',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('geo_key', sa.String(length=50), nullable=False),
    sa.Column('median_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('price_per_sqft', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_per_acre', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('median_days_on_market', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('months_of_supply', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('sales_volume_30d', sa.Integer(), nullable=True),
    sa.Column('sales_volume_90d', sa.Integer(), nullable=True),
    sa.Column('yoy_price_change_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('mom_price_change_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('hpi_index', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('interest_rate_30yr', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('interest_rate_15yr', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('interest_rate_5yr_arm', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('raw_sources', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_data_geo_key'), 'market_data', ['geo_key'], unique=False)
    op.create_table('model_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('trained_at', sa.DateTime(), nullable=False),
    sa.Column('training_samples', sa.Integer(), nullable=True),
    sa.Column('mape', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('rmse', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('r2', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('feature_importances', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('neighborhood_data',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('geo_key', sa.String(length=50), nullable=False),
    sa.Column('geo_type', sa.Enum('zip', 'tract', 'city', 'county', name='geotype'), nullable=False),
    sa.Column('crime_index', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('crime_grade', sa.String(length=2), nullable=True),
    sa.Column('median_household_income', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('population_growth_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('owner_occupied_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('median_home_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('walk_score', sa.Integer(), nullable=True),
    sa.Column('transit_score', sa.Integer(), nullable=True),
    sa.Column('bike_score', sa.Integer(), nullable=True),
    sa.Column('school_rating_avg', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('demographics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_sources', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_neighborhood_data_geo_key'), 'neighborhood_data', ['geo_key'], unique=False)
    op.create_table('properties',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('address_line1', sa.String(length=255), nullable=False),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('zip_code', sa.String(length=10), nullable=False),
    sa.Column('county', sa.String(length=100), nullable=True),
    sa.Column('lat', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('lng', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('beds', sa.Integer(), nullable=True),
    sa.Column('baths', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('sqft', sa.Integer(), nullable=True),
    sa.Column('lot_size_acres', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('year_built', sa.Integer(), nullable=True),
    sa.Column('property_type', sa.Enum('single_family', 'condo', 'multi_family', 'townhouse', 'land', 'commercial', 'other', name='propertytype'), nullable=True),
    sa.Column('current_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('list_date', sa.Date(), nullable=True),
    sa.Column('days_on_market', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('photo_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_properties_external_id'), 'properties', ['external_id'], unique=False)
    op.create_index(op.f('ix_properties_zip_code'), 'properties', ['zip_code'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('tier', sa.Enum('free', 'pro', name='usertier'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('deal_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('grade', sa.String(length=2), nullable=False),
    sa.Column('verdict', sa.String(length=50), nullable=True),
    sa.Column('ai_analysis', sa.Text(), nullable=True),
    sa.Column('score_components', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('key_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('risks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('opportunities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deal_scores_property_id'), 'deal_scores', ['property_id'], unique=False)
    op.create_table('price_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('list', 'sale', 'delist', 'price_change', name='priceeventtype'), nullable=False),
    sa.Column('price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_history_property_id'), 'price_history', ['property_id'], unique=False)
    op.create_table('saved_properties',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('price_snapshot', sa.Float(), nullable=True),
    sa.Column('alert_enabled', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_properties_property_id'), 'saved_properties', ['property_id'], unique=False)
    op.create_index(op.f('ix_saved_properties_user_id'), 'saved_properties', ['user_id'], unique=False)
    op.create_table('saved_searches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('search_params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('alert_enabled', sa.Boolean(), nullable=False),
    sa.Column('alert_frequency', sa.Enum('immediate', 'daily', 'weekly', name='alertfrequency'), nullable=False),
    sa.Column('last_alerted_at', sa.DateTime(), nullable=True),
    sa.Column('last_results_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_searches_user_id'), 'saved_searches', ['user_id'], unique=False)
    op.create_table('tax_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('assessed_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('tax_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tax_history_property_id'), 'tax_history', ['property_id'], unique=False)
    op.create_table('alert_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('saved_search_id', sa.UUID(), nullable=True),
    sa.Column('job_type', sa.Enum('price_drop', 'new_listing', 'deal_score_change', name='alertjobtype'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', name='alertjobstatus'), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('results_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['saved_search_id'], ['saved_searches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_jobs_user_id'), 'alert_jobs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alert_jobs_user_id'), table_name='alert_jobs')
    op.drop_table('alert_jobs')
    op.drop_index(op.f('ix_tax_history_property_id'), table_name='tax_history')
    op.drop_table('tax_history')
    op.drop_index(op.f('ix_saved_searches_user_id'), table_name='saved_searches')
    op.drop_table('saved_searches')
    op.drop_index(op.f('ix_saved_properties_user_id'), table_name='saved_properties')
    op.drop_index(op.f('ix_saved_properties_property_id'), table_name='saved_properties')
    op.drop_table('saved_properties')
    op.drop_index(op.f('ix_price_history_property_id'), table_name='price_history')
    op.drop_table('price_history')
    op.drop_index(op.f('ix_deal_scores_property_id'), table_name='deal_scores')
    op.drop_table('deal_scores')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_properties_zip_code'), table_name='properties')
    op.drop_index(op.f('ix_properties_external_id'), table_name='properties')
    op.drop_table('properties')
    op.drop_index(op.f('ix_neighborhood_data_geo_key'), table_name='neighborhood_data')
    op.drop_table('neighborhood_data')
    op.drop_table('model_metrics')
    op.drop_index(op.f('ix_market_data_geo_key'), table_name='market_data')
    op.drop_table('market_data')
    # ### end Alembic commands ###
